owner: asadbashir7755
repo: portfilio-website-status-page

sites:
  - name: Commit to Deploy
    url: https://committodeploy.dev

status-website:
  logoUrl: https://committodeploy.dev/favicon.ico
  name: Commit to Deploy Status
